# Generated by Django 4.1 on 2023-03-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=150)),
                ("zipCode", models.CharField(max_length=8)),
                ("street", models.CharField(max_length=150)),
                ("number", models.IntegerField()),
            ],
        ),
    ]
