# Generated by Django 4.0 on 2023-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_avaliable'),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='carts', to='products.Product'),
        ),
    ]
