# Generated by Django 4.1 on 2023-03-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("username",)},
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_common",
        ),
    ]
