# Generated by Django 4.1.7 on 2023-03-08 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="data_criacao",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="data_atualizacao",
            new_name="updated_at",
        ),
    ]
