# Generated by Django 4.0 on 2023-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pedido Realizado', 'Pr'), ('Em Andamento', 'Ea'), ('Entregue', 'En')], max_length=20),
        ),
    ]
