<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-08 12:38
=======
# Generated by Django 4.1.7 on 2023-03-08 15:17
>>>>>>> 8e383a9f284a5f7697c66344825b5ab6463612b3

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
=======
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("category", models.CharField(max_length=50)),
                ("currenty_inventory", models.IntegerField()),
>>>>>>> 8e383a9f284a5f7697c66344825b5ab6463612b3
            ],
        ),
    ]
