# Generated by Django 4.0 on 2023-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
